using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using swcb01.Models;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Security;

namespace swcb01.Controllers
{
    public class ImageRetrievalController : Controller
    {
        // GET: ImageRetrieval
        public ActionResult Index()
        {
            
           return View();
                
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {

            System.IO.DirectoryInfo di = new DirectoryInfo(Server.MapPath("~/SearchImage"));


            foreach (FileInfo f in di.GetFiles())
            {
                f.Delete();
            }



            string fileName = null;
            if (file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/SearchImage"), fileName);
                file.SaveAs(path);
            }

            

            string resultString = run_cmd(fileName);


            RootObject result = null;
            result = JsonConvert.DeserializeObject<RootObject>(resultString);

            ViewBag.FileName = fileName;


            return View(result.Images);
        }

       

        public string run_cmd(string fileName)
        {
            //var user = System.Security.Principal.WindowsIdentity.GetCurrent().User;
            //var userName = user.Translate(typeof(System.Security.Principal.NTAccount));

            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "D:/XinYu/Anaconda3/envs/apple/python.exe";
            //string cmd = "D:/XinYu/109_swcbProject_server/pyScripts/02_02_01_AE_predictToAnnoyIndex.py";
            string cmd = Path.Combine(Server.MapPath("~/pyScripts"), "02_02_01_AE_predictToAnnoyIndex.py");
            start.Arguments = string.Format("\"{0}\" --qi \"{1}\"", cmd, fileName);
            string passwordStr = "swater0";
            SecureString password = new SecureString();
            foreach (char c in passwordStr)
                password.AppendChar(c);
            start.Password = password;
            start.UserName = "409LAB00";

            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            string fileName = null;
            if (file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/SearchImage"), fileName);
                file.SaveAs(path);
            }

            string result = run_cmd(fileName);



            return View();
            //return RedirectToAction("Index", new { imagesJson = result });
        }

        public class RootObject
        {
            public List<ImageModel> Images { get; set; }
        }
    }
}